app/tasks/models.py
#!/usr/bin/python3
"""Base model for the project"""
import uuid
from datetime import datetime


class Task:
    """Task class"""

    def __init__(self, title: str, description: str, due_date, due_date_date) -> None:
        """Initializes an instance of the Task class"""
        self.__id = uuid.uuid4()
        self.title = title
        self.description = description
        self.due_date = due_date
        self.due_date_date = due_date_date
        self.__created_at = datetime.now()
        self.__updated_at = datetime.now()
    
    @property
    def id(self):
        """Returns the id of the task"""
        return self.__id

    @property
    def created_at(self):
        """Returns the title of the task"""
        return self.__created_at

    @property
    def updated_at(self):
        """Returns the title of the task"""
        return self.__updated_at

    def to_dict(self):
        """Returns a dictionary representation of the task"""
        return {
            'id': str(self.id),
            'title': self.title,
            'description': self.description,
            'due_date': self.due_date,
            'due_date_date': self.due_date_date,
            'created_at': self.__created_at.strftime('%Y-%m-%dT%H:%M:%S.%f'),
            'updated_at': self.__updated_at.strftime('%Y-%m-%dT%H:%M:%S.%f')
        }
    
    @created_at.setter
    def created_at(self, value):
        """Sets the created_at attribute to the current datetime"""
        self.__created_at = value

    @updated_at.setter
    def updated_at(self, value):
        """Sets the updated_at attribute to the current datetime"""
        self.__updated_at = value

app/__init__.py
from flask import Flask

app = Flask(__name__)

from .tasks.routes import task

app.register_blueprint(task)

app/tasks/routes.py
from flask import Response, Blueprint, render_template, request, redirect, url_for, Response, jsonify
from icalendar import Calendar, Event
from datetime import datetime
import uuid
from .models import Task

task = Blueprint('tasks', __name__, url_prefix='/')
tasks = []

@task.route('', methods=['GET'], strict_slashes=False)
def welcome_page():
    """This method gets tasks for the user"""
    return render_template('welcome.html')

# @task.route('/create_task/<id>', methods=['GET', 'POST', 'DELETE'], strict_slashes=False)
@task.route('/create_task', defaults={'id': None}, methods=['GET', 'POST'], strict_slashes=False)
@task.route('/create_task/<id>', methods=['DELETE', 'PUT'], strict_slashes=False)
def create_task(id=None):
    """This method gets tasks for the user"""
    if request.method == 'GET':
        pass
        return render_template('app.html', tasks=tasks)
    # tasks = []
    elif request.method == 'POST':
        title = request.form.get('title')
        description = request.form.get('description')
        due_date_str = request.form.get('due_date')

        if due_date_str is None:
            return "Due date is required"

        try:
            due_date = datetime.strptime(due_date_str, '%Y-%m-%d')
            due_date_date = due_date.date()
        except ValueError:
            return "Invalid due date format. Please use the format 'YYYY-MM-DD'"

        # Perform any validation if needed

        # Create a task (replace with your actual task creation logic)
        if tasks is None:
            tasks.add(Task(title=title, description=description, due_date=due_date, due_date_date=due_date_date).to_dict())  
        elif due_date_str:
            tasks.append(Task(title=title, description=description, due_date=due_date, due_date_date=due_date_date).to_dict())
        # Save the task (if you have a database, add code to save the task)
        
        """This method gets tasks for the user"""
        return redirect(url_for('tasks.create_task'))

    elif request.method == 'DELETE':
        """Deletes a particular task"""
        for task in tasks:
            if task['id'] == id:
                print(task)
                print(task['id'])
                print(id)
                print(task['id'] == id)
                tasks.remove(task)
                return redirect(url_for('tasks.create_task')), 

        return "Task not found", 404
    
    elif request.method == 'PUT':
        """Edits a particular task"""
        for task in tasks:
            if task['id'] == id:
                print(task)
                print(task['id'])
                print(id)
                print(task['id'] == id)
                new_title = request.form.get('mtitle')
                print(new_title)
                new_description = request.form.get('mdescription')
                print(new_description)
                new_date = request.form.get('mdue_date')
                print(new_date)
                task['title'] = new_title
                task['description'] = new_description
                task['due_date'] = new_date
                task['due_date_date'] = new_date
                task['updated_at'] = datetime.now().strftime('%Y-%m-%dT%H:%M:%S.%f')
                print(task)
                return redirect(url_for('tasks.create_task')) 

        return "Task not found", 404
 

@task.route('/export-calendar', strict_slashes=False)
def export_calendar():
    # tasks = []  # Replace with tasks retrieval logic
    global tasks
    cal = Calendar()

    for task in tasks:
        event = Event()
        event.add('summary', task.title)
        event.add('description', task.description)
        # Assuming task has a 'due_date' attribute
        event.add('dtstart', task.due_date)
        event.add('dtend', task.due_date)
        event.add('dtstamp', datetime.now())
        cal.add_component(event)

    response = Response(cal.to_ical(), mimetype="text/calendar")
    response.headers["Content-Disposition"] = "attachment; filename=tasks.ics"
    tasks = []
    return response

app/templates/app.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/app.css') }}">
    <!-- <link rel="script href="{{ url_for('static', filename='styles/reset.css') }}"> -->
    <title>Charley Do Am</title>
</head>

<body>
    <header>
        <div class="container">
            <a href="/"><h1>Charley<span class="highlight">DoAm</span></h1></a>
        </div>
    </header>

    <main>
        <div class="container">
            <div class="tasks">
                {% if tasks|length == 0 %}
                <p id="no_tasks">No tasks added yet. Add one here.</p>
                {% endif %}
                {% for task in tasks %}
                <div class="task">
                    <p class="title"><strong>{{ task.title }}</strong></p>
                    <p class="description">{{ task.description }}</p>
                    <p class="date">{{ task.due_date_date}}</p>
                    <button id="editBtn" class="btn edit-btn" onclick="editTask('{{ task.id }}')">Edit</button>
                    <button class="btn delete-btn" onclick="deleteTask('{{ task.id }}')">Delete</button>
                </div>
                {% endfor %}
            </div>

            <!-- Modal -->
            <div id="editModal" class="modal">
                <div class="modal-content">
                    <span class="close">&times;</span>
                    <form id="editForm" >
                        <label for="title">Title:</label><br>
                        <input type="text" id="title" name="mtitle"><br>
                        <label for="description">Description:</label><br>
                        <input type="text" id="description" name="mdescription"><br>
                        <label for="date">Date</label>
                        <input type="date" id="date" name="mdue_date" required><br>
                        <!-- Add other fields as necessary -->
                        <input type="submit" value="Save">
                    </form>
                </div>
            </div>
       
            <div class="task-form">
                <form action="{{ url_for('tasks.create_task') }}" method="post">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" name="title" id="title" placeholder="Title" required>
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea name="description" id="description" placeholder="Description" rows="5"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="date">Date</label>
                        <input type="date" id="date" name="due_date" required>
                    </div>
                    <button type="submit" class="btn add-btn">Add Task</button>
                    <a class="btn export-btn " href="{{ url_for('tasks.export_calendar') }}" class="export-link">Export to Calendar</a>
                </form>
            </div>
        </div>
    </main>
    <script src="{{ url_for('static', filename='scripts/index.js') }}"></script>
</body>

</html>

app/templates/index.html
<!-- templates/index.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/reset.css') }}">
    <title>Task Manager</title>
</head>

<body>
    <div class="container">
        <h1>ChaleyDoAm Task Manager</h1>
    </div>

    <div class="all-container">
        <div class="form-container">
            <form action="{{ url_for('tasks.create_task') }}" method="post">
                <label for="title">Task Title:</label>
                <input type="text" id="title" name="title" required>

                <label for="description">Task Description:</label>
                <textarea id="description" name="description" rows="4"></textarea>

                <label for="due_date">Due Date:</label>
                <input type="date" id="due_date" name="due_date" required>

                <button type="submit">Add Task</button>
            </form>

            <a href="{{ url_for('tasks.export_calendar') }}" class="export-link">Export to Calendar</a>
        </div>
        <div class="tasks-container">
            <div class="sub_container">
                <ul>
                    {% for task in tasks %}
                    <li class="task_cube">
                        <!-- <div class="flip-card">
                            <div class="flip-card-inner">
                              <div class="flip-card-front">
                                <img src="img_avatar.png" alt="Avatar" style="width:300px;height:300px;">
                              </div>
                              <div class="flip-card-back">
                                <h1>John Doe</h1> 
                                <p>Architect & Engineer</p> 
                                <p>We love that guy</p>
                              </div>
                            </div>
                          </div> -->
                        
                        
                        <span>{{ task.title }} - {{ task.description }} - {{ task.due_date_date
                            }}</span>
                        <button id="editButton">Edit</button>
                        <!-- <button onclick="create_task(task.id)" method="delete">Delete</button> -->
                        <button id="deleteButton" onclick="deleteTask('{{ task.id }}')">Delete</button>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <script>
        function deleteTask(id) {
            const url = '/create_task/' + id;
            const domain = window.location.origin;
            const fullUrl = domain + url;
            fetch(fullUrl, {
                method: 'DELETE',
            })
                .then(response => {
                    // if (!response.ok) {
                    //     throw new Error('Network response was not ok');
                    // }
                    console.log(response);
                    location.reload();
                })
                .catch((error) => {
                    console.error('Error:', error);
                });
        }
    </script>
</body>

</html>

app/templates/welcome.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to ChaleyDoAm</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/welcome.css') }}">
</head>

<body>
    <div id="page1" class="page my_bg">
        <div class="container">
            <!-- <img src="{{ url_for('static', filename='images/bckground1.png') }}" alt=""> -->
            <h1>Welcome to ChaleyDoAm</h1>
            <p>A task management app to help you stay organized and productive.</p>
            <!-- <br><br><br><br><br> -->
            <div class="slideshow">
                <div style="position: relative; width: 100%; height: 0; padding-top: 56.2225%;
                padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
                border-radius: 8px; will-change: transform;">
                           <iframe loading="lazy"
                               style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
                               src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAF1ipK1krY&#x2F;view?embed"
                               allowfullscreen="allowfullscreen" allow="fullscreen">
                           </iframe>
                       </div>
            </div>
            <!-- <a href="#" class="btn">Get Started</a> -->
    
            <!-- <img src="/app/static/images/background.jpg" alt="picture"> -->

            <!-- <a href="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAF1ipK1krY&#x2F;view?utm_content=DAF1ipK1krY&amp;utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link" -->
                <!-- target="_blank" rel="noopener">Tech Website in Teal White Navy Gradients Style</a> by segmented79 -->
                <a href="#page2" class="btn">Features</a>
                <a href="/create_task/" class="btn">Get Started</a>
                <a href="#page3" class="btn">About</a>
        </div>
    </div>
    <div id="page2" class="page">
        
        <div class="tutorial-cards">
            <div class="card">
                <img src="{{ url_for('static', filename='images/edit_feature.png') }}" alt="Tutorial Card 1">
                <h2>Edit Feature</h2>
                <p>Made a mistake? Don't stress. You can easily edit your tasks just by clicking this button.</p>
            </div>
            <div class="card">
                <img src="{{ url_for('static', filename='images/delete_feature.png') }}" alt="Tutorial Card 2">
                <h2>Delete Feature</h2>
                <p>Maybe you've changed your mind and no longer want to add that particular task to your list. This button will come in handy.</p>
            </div>
            <div class="card">
                <img src="{{ url_for('static', filename='images/export_feature.png') }}" alt="Tutorial Card 3">
                <h2>Export Feature</h2>
                <p>Take your tasks with you wherever you go and on which ever device you want. This feature produces a calendar file.
                    This file is useful for sharing your tasks with others or for importing your tasks into another calendar app.</p>
                </p>
            </div>
        </div>
    </div>
    <div id="page3" class="page">
        <div class="container">
            <hr>
            <h1>About</h1>
            <div class="container">
            <p>ChaleyDoAm is a task management app that helps you stay organized and productive. It is a simple and easy to use app that allows you to create tasks and manage them.</p>
            <p>ChaleyDoAm is a project created by a group of students from the ALX SE program. It was created as part of a Software Engineering course.</p>
            <p>ChaleyDoAm is a Pidgin word that means "Bro do it".</p>
            <p>ChaleyDoAm is a free app that is available to anyone who wants to use it.</p>
            <p>ChaleyDoAm is a web app that can be accessed from any device that has an internet connection.</p>
            <br>
            <a href="https://github.com/reginaldbdanso/ChaleyDoAM">Github</a>
            <br><br><hr>
        </div>
        </div>
    </div>
    <div id="page4" class="page">
    <!-- BEGIN: contact-us-section -->
    <div id="page7" class="page">
        <div class="container contact_us">
            <h1>Contact Us</h1>
            <p>Have any questions or feedback? We'd love to hear from you!</p>
            <form>
                <div class="form-group">
                    <label for="name">Name</label>
                    <span><input type="text" id="name" name="name" placeholder="Your name"></span>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" placeholder="Your email">
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea id="message" name="message" placeholder="Your message"></textarea>
                </div>
                <button type="submit" class="btn">Send Message</button>
            </form>
        </div>
    </div>
    <!-- END: contact-us-section -->
    </div>
   
</body>

</html>